function [ predicted ] = test_Perceptron( test,w )
%TEST_PERCEPTRON Given a test dataset and a model generated when a perceptron
%algorithm is trained. Classify the instances of the test dataset.
%
%   ACTIVATION FUNCTION: STEP
%
%   INPUT:
%       - test: test dataset that the function has to classify.
%       - w: the model generated by when the adaboost algorithm is
%       trained
%   OUTPUT:
%       - predicted: the predicted labels for the given dataset.

    %Ini. the array of predicted labels.
    predicted = zeros(size(test,1),1);
    
    %Dataset value
    offset = -1;
    
    %Test each test dataset input using the given model.
    for p = 1:size(test,1)
        predicted(p) = [test(p,:),offset]*w;
        if predicted(p) >= 0
            predicted(p) = 1;
        else
            predicted(p) = 0;
        end
    end
    
    %Return the prediction.
    predicted = predicted - 0.5;
    predicted = sign(predicted);
end

