function [ predicted ] = test_PerceptronSigmoid( test, w )
%TEST_PERCEPTRONSIGMOID Given a test dataset and a model generated when a perceptron
%algorithm is trained. Classify the instances of the test dataset.
%
%   ACTIVATION FUNCTION: LOGISTIC
%
%   INPUT:
%       - test: test dataset that the function has to classify.
%       - w: the model generated by when the adaboost algorithm is
%       trained
%   OUTPUT:
%       - predicted: the predicted labels for the given dataset.

    %Ini. the array of predicted labels.
    predicted = zeros(size(test,1),1);
    
    %The value of the offset/threshold
    offset = -1;
    
    %Classify each member of the test set using the given model w.
    for p = 1:size(test,1)
        predicted(p) = 1/(1+exp(-([test(p,:),offset]*w)));
    end
    
    predicted = predicted - 0.5;
    predicted = sign(predicted);
end

